api_platform:
    eager_loading:
        max_joins: 100
        force_eager: false
    title: Beyin LQ
    version: 1.0.0
    defaults:
        # serializer_context:
        #     enable_max_depth: true
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        patch_formats:
            json: ['application/merge-patch+json']
        formats:
            jsonld: ['application/ld+json']
            json: ['application/json']
            html: ['text/html']
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']