api_platform:
    title: Beyin LQ
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']  
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']